apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8test
  template:
    metadata:
      labels:
        app: k8test
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432

      - name: k8test
        image: alxn787/k8test:latest
        ports:
        - containerPort: 3000 

      
